/**
 * ReportViewer - Feature Component
 * 
 * Displays the final research report with markdown rendering
 * and download functionality (Markdown + PDF).
 */
import React from 'react';
import { motion } from 'framer-motion';
import { FileText, FileCode } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from '@react-pdf/renderer';
import { Button } from './ui/Button';
import { Card } from './ui/Card';
import { SourceViewer } from './SourceViewer';
import { useResearchStore } from '../stores/researchStore';

// PDF Styles
const pdfStyles = StyleSheet.create({
  page: {
    padding: 50,
    fontSize: 11,
    fontFamily: 'Helvetica',
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#333',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#000',
  },
  metadata: {
    fontSize: 10,
    color: '#666',
    fontStyle: 'italic',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    backgroundColor: '#f0f0f0',
    padding: 6,
    color: '#000',
  },
  paragraph: {
    marginBottom: 8,
    textAlign: 'justify',
    color: '#333',
  },
  executiveSummary: {
    backgroundColor: '#f5f5f5',
    padding: 12,
    marginBottom: 15,
    borderLeftWidth: 3,
    borderLeftColor: '#333',
  },
  executiveTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#000',
  },
  sourceItem: {
    fontSize: 9,
    marginBottom: 6,
    paddingLeft: 15,
  },
  sourceTitle: {
    fontWeight: 'bold',
  },
  sourceUrl: {
    color: '#0066cc',
    fontSize: 8,
  },
  confidenceBox: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#f9f9f9',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  confidenceTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 8,
    color: '#999',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    paddingTop: 8,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 30,
    right: 50,
    fontSize: 8,
    color: '#999',
  },
  referencesSection: {
    marginTop: 10,
  },
  referencesTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#000',
  },
});

// Custom link component that opens in new tab (for UI)
const MarkdownLink = ({ href, children }: { href?: string; children?: React.ReactNode }) => {
  return (
    <a 
      href={href} 
      target="_blank" 
      rel="noopener noreferrer"
      className="text-blue-400 hover:text-blue-300 hover:underline"
    >
      {children}
    </a>
  );
};

// PDF Document Component
interface PDFReportProps {
  title: string;
  date: string;
  word_count: number;
  sources_count: number;
  executive_summary: string;
  sections: Array<{ heading: string; content: string }>;
  sources: Array<{ title: string; url: string; reliability: string }>;
  confidence_assessment: string;
}

const ReportPDFDocument: React.FC<PDFReportProps> = ({
  title,
  date,
  word_count,
  sources_count,
  executive_summary,
  sections,
  sources,
  confidence_assessment,
}) => {
  // Clean text for PDF (remove markdown)
  const cleanText = (text: string) => {
    return text
      .replace(/\[🔗([^\]]+)\]\(([^)]+)\)/g, '$1')
      .replace(/\*\*/g, '')
      .replace(/\*/g, '')
      .replace(/#/g, '');
  };

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>{title}</Text>
          <Text style={pdfStyles.metadata}>
            Research Report | {date} | {word_count} words | {sources_count} sources
          </Text>
        </View>

        {/* Executive Summary */}
        <View style={pdfStyles.executiveSummary}>
          <Text style={pdfStyles.executiveTitle}>Executive Summary</Text>
          {cleanText(executive_summary).split('\n').filter(p => p.trim()).map((para, idx) => (
            <Text key={idx} style={pdfStyles.paragraph}>
              {para}
            </Text>
          ))}
        </View>

        {/* Sections */}
        {sections.map((section, index) => (
          <View key={index} style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>
              {index + 1}. {section.heading}
            </Text>
            {cleanText(section.content).split('\n\n').filter(p => p.trim()).map((para, pidx) => (
              <Text key={pidx} style={pdfStyles.paragraph}>
                {para}
              </Text>
            ))}
          </View>
        ))}

        {/* Footer on first page */}
        <Text style={pdfStyles.footer}>
          Generated by Deep Research System
        </Text>
        <Text
          style={pdfStyles.pageNumber}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
          fixed
        />
      </Page>

      {/* References Page */}
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.referencesSection}>
          <Text style={pdfStyles.referencesTitle}>References</Text>
          {sources.map((source, index) => (
            <View key={index} style={pdfStyles.sourceItem}>
              <Text>
                {index + 1}. <Text style={pdfStyles.sourceTitle}>{source.title || 'Untitled'}</Text>
                {' '}
                [{source.reliability || 'unknown'}]
              </Text>
              <Text style={pdfStyles.sourceUrl}>{source.url}</Text>
            </View>
          ))}
        </View>

        {/* Confidence Assessment on references page */}
        <View style={pdfStyles.confidenceBox}>
          <Text style={pdfStyles.confidenceTitle}>Confidence Assessment</Text>
          {cleanText(confidence_assessment).split('\n').filter(p => p.trim()).map((para, idx) => (
            <Text key={idx} style={{ fontSize: 10, color: '#333' }}>
              {para}
            </Text>
          ))}
        </View>

        {/* Footer */}
        <Text style={pdfStyles.footer}>
          Generated by Deep Research System
        </Text>
        <Text
          style={pdfStyles.pageNumber}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
          fixed
        />
      </Page>
    </Document>
  );
};

export function ReportViewer() {
  const { finalReport, status } = useResearchStore();

  if (!finalReport || status !== 'completed') return null;

  // Safety checks for report data
  const title = finalReport.title || 'Untitled Report';
  const word_count = finalReport.word_count || 0;
  const sources_used = finalReport.sources_used || [];
  const sections = finalReport.sections || [];
  const executive_summary = finalReport.executive_summary || '';
  const confidence_assessment = finalReport.confidence_assessment || '';

  const handleDownloadMarkdown = () => {
    const markdown = `# ${finalReport.title}

${finalReport.executive_summary}

## Report Details

**Word Count:** ${finalReport.word_count}
**Sources Used:** ${sources_used.length}
**Confidence:** ${finalReport.confidence_assessment}

${finalReport.sections.map(s => `
## ${s.heading}

${s.content}
`).join('\n')}

## Sources

${sources_used.map((s, i) => `${i + 1}. [${s.title || 'Untitled'}](${s.url}) - ${s.reliability || 'unknown'}`).join('\n')}
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.toLowerCase().replace(/\s+/g, '-')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // PDF Document data
  const pdfData: PDFReportProps = {
    title,
    date: new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    }),
    word_count,
    sources_count: sources_used.length,
    executive_summary,
    sections,
    sources: sources_used,
    confidence_assessment,
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full"
    >
      <Card
        title={title}
        subtitle={`${word_count} words • ${sources_used.length} sources`}
        headerAction={
          <div className="flex items-center gap-2">
            <PDFDownloadLink
              document={<ReportPDFDocument {...pdfData} />}
              fileName={`${title.toLowerCase().replace(/\s+/g, '-')}.pdf`}
            >
              {({ loading }) => (
                <Button variant="secondary" size="sm" disabled={loading}>
                  <FileText className="w-4 h-4 mr-2" />
                  {loading ? 'Generating...' : 'PDF'}
                </Button>
              )}
            </PDFDownloadLink>
            <Button variant="secondary" size="sm" onClick={handleDownloadMarkdown}>
              <FileCode className="w-4 h-4 mr-2" />
              Markdown
            </Button>
          </div>
        }
      >
        {/* Executive Summary */}
        <div className="mb-6 p-4 bg-slate-800/50 rounded-lg border border-slate-700/50">
          <h4 className="text-sm font-medium text-slate-400 mb-2 uppercase tracking-wider">
            Executive Summary
          </h4>
          <div className="prose prose-invert prose-sm max-w-none">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{ a: MarkdownLink }}
            >
              {executive_summary}
            </ReactMarkdown>
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section, index) => (
            <div key={index} className="border-b border-slate-800 pb-6 last:border-0">
              <h4 className="text-lg font-semibold text-white mb-3">{section.heading}</h4>
              <div className="prose prose-invert prose-sm max-w-none">
                <ReactMarkdown 
                  remarkPlugins={[remarkGfm]}
                  components={{ a: MarkdownLink }}
                >
                  {section.content}
                </ReactMarkdown>
              </div>
            </div>
          ))}
        </div>

        {/* Sources */}
        <div className="mt-8 pt-6 border-t border-slate-800">
          <SourceViewer sources={sources_used} />
        </div>

        {/* Confidence Assessment */}
        <div className="mt-6 p-4 bg-slate-800/30 rounded-lg">
          <h4 className="text-sm font-medium text-slate-400 mb-2">Confidence Assessment</h4>
          <div className="prose prose-invert prose-sm max-w-none">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{ a: MarkdownLink }}
            >
              {confidence_assessment}
            </ReactMarkdown>
          </div>
        </div>
      </Card>
    </motion.div>
  );
}
